name: fair-risk
channels:
        - conda-forge
dependencies:
        - jupyterlab
        - matplotlib
        - netCDF4
        - numpy
        - pandas
        - seaborn
        - xarray
        - pip:
                - fair
                - aneris-iamc
                - tqdm
                - pooch
